sudo: required
language: ruby
before_install:
  - sudo apt-get install libpcap-dev -qq
  - gem update --system
  - gem --version
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1

branches:
  except:
    - gh-pages
