sudo: required
language: ruby
before_install:
  - sudo apt-get install libpcap-dev -qq
  - gem update --system
  - gem --version
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  except:
    - gh-pages

addons:
  code_climate:
    repo_token: 71107cb58f585bf7506e53f33238f4bd4e9aa87215ed916a5b466ecd9b493209
